M48
; DRILL file {KiCad (6.0.0)} date Mon Dec 27 13:21:01 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-12-27T13:21:01-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.400
%
G90
G05
T1
X50.704Y-6.918
X56.484Y-6.918
T2
X4.0Y-33.0
X15.0Y-33.0
X54.0Y-33.0
X65.0Y-33.0
T3
X9.5Y-33.0
X59.5Y-33.0
T0
M30
